pipeline {
    agent any
    
    environment {
        // Correct way to use credentials in environment block
        AWS_CREDS = credentials('aws-creds')
        DOCKER_IMAGE = 'sareen/simple-web-app'
        KUBE_CONFIG = credentials('kube-config')
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/Sareenh1/web-app-deployment.git'
            }
        }
        
        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    // Using the AWS credentials
                    sh '''
                        export AWS_ACCESS_KEY_ID=$AWS_CREDS_USR
                        export AWS_SECRET_ACCESS_KEY=$AWS_CREDS_PSW
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${env.DOCKER_IMAGE}")
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'kube-config']) {
                    sh 'kubectl apply -f k8s/deployment.yaml'
                    sh 'kubectl apply -f k8s/service.yaml'
                    sh 'kubectl rollout status deployment/web-app-deployment'
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
