pipeline {
    agent any
    
      environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-creds').username
        AWS_SECRET_ACCESS_KEY = credentials('aws-creds').password
        DOCKER_IMAGE          = 'sareen/simple-web-app'
        KUBE_CONFIG           = credentials('kube-config')

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Sareenh1/web-app-deployment.git'
            }
        }
        
        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('docker') {
                    sh 'docker build -t sareen/simple-web-app .'
                    sh 'docker push sareen/simple-web-app'
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                dir('kubernetes') {
                    sh 'kubectl apply -f deployment.yaml'
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
